---
# Значения по умолчанию
jenkins_repo_url:      "https://pkg.jenkins.io/debian-stable"
jenkins_repo_key_url:  "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
jenkins_package:       "jenkins"
java_packages:
  - "openjdk-11-jdk"
jenkins_http_port:     9090
