# teachua-app/templates/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
  annotations: # <<< ADD THIS ANNOTATION BLOCK
    cloud.google.com/backend-config: '{"default": "{{ .Values.frontend.name }}-backend-config"}'

spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
