apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "jenkins-ip"
    kubernetes.io/ingress.allow-http: "true"
    cloud.google.com/backend-config: '{"default": "jenkins-backendconfig"}'
spec:
  ingressClassName: gce
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.jenkins.name }}
                port:
                  number: {{ .Values.jenkins.port }}
