apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jenkins.name }}
  labels:
    app: {{ .Values.jenkins.name }}
  annotations: # <<< ADD THIS ANNOTATION BLOCK
    cloud.google.com/backend-config: '{"default": "{{ .Values.jenkins.name }}-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.jenkins.port }}
      targetPort: {{ .Values.jenkins.port }}
      name: http
    - port: 50000
      targetPort: 50000
      name: agent
  selector:
    app: {{ .Values.jenkins.name }}
