all:
  children:
    frontend:
      hosts:
        16.16.146.25:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_python_interpreter: python3

    backend:
      hosts:
        16.16.146.25:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_python_interpreter: python3

    database:
      hosts:
        localhost:
          ansible_host: terraform-20250703193959674200000001.cnqucmcikyu5.eu-north-1.rds.amazonaws.com
          ansible_connection: local
          ansible_become: false
    
    proxy:
      hosts:
        16.16.146.25:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_python_interpreter: python3

    keys:
      hosts: 
        16.16.146.25:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_python_interpreter: python3
    
    jenkins_controller:
      hosts:
        16.16.146.25:
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_python_interpreter: python3