# ansible/roles/docker_setup/defaults/main.yml
---
# Версия Docker Compose
docker_compose_version: "1.29.2"

# Ссылка на AWS CLI v2 (для x86_64)
aws_cli_download_url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"

# Пакеты Docker для Ubuntu/Debian
docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
